[package]
name = "fs-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.2"
thiserror = "1.0.49"
uuid = { version = "1.4.1", features = ["v4"] }
